name = "ErdosUnitDistanceComparator"
defaultTargets = ["Challenge", "Solution"]

[[require]]
name = "ErdosUnitDistance"
git = "https://github.com/kim-em/erdos-unit-distance.git"
rev = "cd25be5865a60b879fd609b5a53fc828ed45dafb"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
